### ISSUE TITLE
[9주차] 그리디

### ISSUE THREAD

**Issue by KyuhyeongK** [KUkingClass/algorithm-class#8]
# 그리디
재밌어보이는 문제들로 골라봤습니당

(추가) 3일차 파일 정렬하기 3 문제랑 2일차 카드 정렬하기 문제가 너무 똑같아서 3일차 문제 바꿨어요,,

### 폴더 링크
  - 현정
  - 수진
  - 태준
  - [규형](https://github.com/KUkingClass/algorithm-class/tree/main/kyuhyeong/boj/그리디)
  - 지승
  - 미승
-------------

## BOJ
- ### 1일차 [8980 택배](https://www.acmicpc.net/problem/8980)
  - [x] 현정
  - [ ] 수진
  - [ ] 태준
  - [x] 규형
  - [ ] 지승
  - [ ] 미승

- ### 2일차 [1715 카드 정렬하기](https://www.acmicpc.net/problem/1715)
  - [x] 현정
  - [ ] 수진
  - [ ] 태준
  - [x] 규형
  - [ ] 지승
  - [ ] 미승

- ### 3일차 [21758 꿀 따기](https://www.acmicpc.net/problem/21758)
  - [x] 현정
  - [ ] 수진
  - [ ] 태준
  - [x] 규형
  - [ ] 지승
  - [ ] 미승

- ### 4일차 [2212 센서](https://www.acmicpc.net/problem/2212)
  - [ ] 현정
  - [ ] 수진
  - [ ] 태준
  - [x] 규형
  - [ ] 지승
  - [ ] 미승

## Programmers
- ### 5일차 [행렬 테두리 회전하기](https://school.programmers.co.kr/learn/courses/30/lessons/77485)
  - [x] 현정
  - [ ] 수진
  - [ ] 태준
  - [x] 규형
  - [ ] 지승
  - [ ] 미승

- ### 6일차 [괄호 회전하기](https://school.programmers.co.kr/learn/courses/30/lessons/76502)
  - [ ] 현정
  - [ ] 수진
  - [ ] 태준
  - [x] 규형
  - [ ] 지승
  - [ ] 미승

**Comment by melonturtle** [comment]
대박 감사합니다... 🙇🏻‍♀️
